title: <p allign="Center">Ashish Khatkalle</p>
logo: /assets/img/logo.png
description:
<p align="center">
<br>
Pursuing executive PG in ML and AI. Currently working as structural Engineer for more than 6 years. 
</p>
theme: jekyll-theme-minimal
